name: Generate Charts

on:
  schedule:
    - cron: "*/23 * * * *"  # Runs every 23 minutes
  workflow_dispatch:        # Allows manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log workflow start time
        run: echo "Workflow started at $(date)"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate charts
        run: |
          python allcharts.py

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git reset --hard
          cp -r charts/* .
          git add .
          git commit -m "Update charts on GitHub Pages"
          git push --force origin gh-pages

      - name: Log workflow completion time
        run: echo "Workflow completed at $(date)"
