name: Generate Charts

on:
  schedule:
    - cron: "*/14 * * * *"  # Runs every 14 minutes
  workflow_dispatch:        # Allows manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log workflow start time
        run: echo "Workflow started at $(date)"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate charts
        run: |
          python allcharts.py

      - name: Move final charts
        run: |
          mkdir -p charts
          mv charts_dev/* charts

      - name: Log workflow completion time
        run: echo "Workflow completed at $(date)"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/*.png charts/*.json
          git diff-index --quiet HEAD || git commit -m "Auto-update charts (moved from charts_dev)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
