name: Generate Charts

on:
  schedule:
    - cron: "*/2300 * * * *"  # Runs every 23 minutes
  workflow_dispatch:        # Allows manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log workflow start time
        run: echo "Workflow started at $(date)"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate charts
        run: |
          python allcharts.py

      - name: Debug charts_dev directory before moving
        run: |
          echo "Contents of charts_dev before moving:"
          ls -l charts_dev || echo "charts_dev directory does not exist"

      - name: Move final charts
        run: |
          mkdir -p charts
          mv charts_dev/* charts || echo "No files to move"

      - name: Debug charts directory after moving
        run: |
          echo "Contents of charts after moving:"
          ls -l charts || echo "charts directory is empty"

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p temp_deploy
          cp -r * temp_deploy/  # Copy everything to a temporary directory
          git checkout --orphan gh-pages
          git reset --hard
          mv temp_deploy/* .  # Move everything back to the root
          rm -rf temp_deploy
          git add .
          git commit -m "Update GitHub Pages with full directory structure"
          git push --force origin gh-pages

      - name: Log workflow completion time
        run: echo "Workflow completed at $(date)"
